/**
 * Catalog images are generated by `bun run assets` into `src/assets/hairstyles`
 * and resolved here so Astro's image pipeline can derive responsive, hashed
 * AVIF/WebP variants at build time.
 */

const catalog = import.meta.glob<{ default: ImageMetadata }>(
	'../assets/hairstyles/*.webp',
	{ eager: true },
);

const byId = new Map<string, ImageMetadata>(
	Object.entries(catalog).map(([path, mod]) => [
		path.split('/').pop()!.replace('.webp', ''),
		mod.default,
	]),
);

export function hairImage(id: string): ImageMetadata {
	const image = byId.get(id);
	if (!image) {
		throw new Error(
			`No catalog image for "${id}". Run \`bun run assets\` to regenerate.`,
		);
	}
	return image;
}

export const hasHairImage = (id: string): boolean => byId.has(id);
